del /s /q .\ipch
del /s /q .\Debug\*.obj
del /s /q .\Debug\*.tlog
del /s /q .\Debug\*.log
del /s /q .\Debug\*.lastbuildstate
del /s /q .\Debug\*.unsuccessfulbuild
del /s /q .\Debug\*.pdb
del /s /q .\Debug\*.idb
del /s /q .\Release\*.obj
del /s /q .\Release\*.tlog
del /s /q .\Release\*.log
del /s /q .\Release\*.lastbuildstate
del /s /q .\Release\*.unsuccessfulbuild
del /s /q .\Release\*.pdb
del /s /q .\Release\*.idb
del /s /q .\*.sdf
rmdir /s /q .\ipch